name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - name: Upload HTML
        uses: actions/upload-artifact@v3
        with:
          name: index.html
          path: release/index.html
  release:
    name: Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
      - name: Download index.html
        uses: actions/download-artifact@v3
        with:
          name: index.html
      - name: Release artifact
        if: ${{ steps.release.outputs.release_created }}
        uses: softprops/action-gh-release@v1
        with:
          files: release/index.html
