name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - name: Upload HTML
        uses: actions/upload-artifact@v3
        with:
          name: index.html
          path: release/index.html
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "index.html"
        bodyFile: "CHANGELOG.md"